### ISSUE TITLE
Using debspawn's -c flag crashes with error message

### ISSUE THREAD

**Issue by jeremiah** [lkorigin/debspawn#18]
```
debspawn -c fake-config-file 
Traceback (most recent call last):
  File "/usr/local/bin/debspawn", line 11, in <module>
    sys.exit(cli.run(thisfile, sys.argv[1:]))
  File "/usr/lib/python3/dist-packages/debspawn/cli.py", line 393, in run
    args.func(args)
AttributeError: 'Namespace' object has no attribute 'func'
```

**Comment by ximion** [comment]
Yeah, you need a subcommand, just the flag won't do it (but debspawn should tell you that instead of crashing ^^)
